services:

    angelov_result_lists.pagination.url_generator:
        class: 'Angelov\ResultLists\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\RoutingPaginationUrlGenerator'
        arguments:
            - '@router'
            - '@angelov_result_lists.current_page_resolver'
            - '@angelov_result_lists.pagination.url_generator.routing_url_generator.route_name_resolver'
            - '@angelov_result_lists.pagination.url_generator.routing_url_generator.url_properties_resolver'

    angelov_result_lists.current_page_resolver:
        class: 'Angelov\ResultLists\ResultLists\Pagination\CurrentPageResolvers\RequestCurrentPageResolver'
        arguments: ['@request_stack']

    angelov_result_lists.pagination.url_generator.routing_url_generator.url_properties_resolver:
        class: 'Angelov\ResultLists\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\UrlPropertiesResolver\RequestUrlPropertiesResolver'
        arguments: ['@request_stack']

    angelov_result_lists.pagination.url_generator.routing_url_generator.route_name_resolver:
        class: 'Angelov\ResultLists\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\RouteNameResolver\RequestRouteNameResolver'
        arguments: ['@request_stack']

    angelov_result_lists.pagination.page_existence_checker:
        class: 'Angelov\ResultLists\ResultLists\Pagination\PageExistenceChecker\PageExistenceChecker'

    angelov_result_lists.pagination.renderers.twig:
        class: 'Angelov\ResultLists\ResultLists\Pagination\Renderers\TwigPaginationRenderer'
        arguments:
            - '@twig'
            - '@angelov_result_lists.pagination.url_generator'
            - '@angelov_result_lists.current_page_resolver'
            - '@angelov_result_lists.pagination.page_existence_checker'

    angelov_result_lists.pagination.twig.extension:
        class: 'Angelov\ResultLists\ResultLists\Pagination\PaginationRendererTwigExtension'
        arguments: ['@angelov_result_lists.pagination.renderers.twig']
        tags:
            - { name: 'twig.extension' }
